name: 'fetch-captain'
description: 'Fetch captain'
author: 'yjl9903'

inputs:
  roomid:
    required: true
    description: '直播房间id'
  ruid:
    required: true
    description: 'up主uid'

runs:
  using: 'node16'
  main: 'dist/index.js'
